export const GET_ALL_RSVPS_REQUEST = 'GET_ALL_RSVPS_REQUEST';
export const GET_ALL_RSVPS_SUCCESS = 'GET_ALL_RSVPS_SUCCESS';
export const GET_ALL_RSVPS_FAILURE = 'GET_ALL_RSVPS_FAILURE';
export const GET_RSVP_INFO = 'GET_RSVP_INFO';
export const RSVP_UPDATE_REQUEST = 'RSVP_UPDATE_REQUEST';
export const RSVP_UPDATE_SUCCESS = 'RSVP_UPDATE_SUCCESS';
export const RSVP_UPDATE_FAILURE = 'RSVP_UPDATE_FAILURE';
